name: Continuous Integration

on:
  push:
    branches:
      - feature/*
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Set up Conan
#        uses: turtlebrowser/get-conan@v1.2

      - name: Install Conan
        # install pip3, conan, cmake, ninja, gcc, g++, make, libstdc++11
        run: |
          pip3 install wheel setuptools
          pip3 install conan
          export PATH=$PATH:/home/runner/.local/bin
          echo $PATH
          conan --version

      - name: Install dependencies
        run: |
          mkdir build
          cd build
          conan profile detect
          conan install .. --build=missing

      - name: Build project
        run: |
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . --config Release -- -j4

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build

  test:
    name: Run GTests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: build
      - name: Run Test
        run: |
          cd build
          ctest -C Release -j4 --output-on-failure